# Generated by Django 3.2.19 on 2023-05-28 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_repaired_car_mechanics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repaired',
            old_name='Mechanic',
            new_name='mechanic',
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartype',
            name='revenue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='description',
            field=models.TextField(default=18),
        ),
    ]
