# Generated by Django 4.1.7 on 2023-06-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20230528_0147'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cartype',
            index=models.Index(fields=['revenue'], name='first_app_c_revenue_952b01_idx'),
        ),
    ]
