# Generated by Django 4.1.7 on 2023-06-05 12:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('first_app', '0004_cartype_first_app_c_revenue_952b01_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=70)),
                ('last_name', models.CharField(default='', max_length=70)),
                ('about', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('gender', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('birthday', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('email', models.EmailField(max_length=75, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
